/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authedRouteRouteImport } from './routes/(authed)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authedTeamRouteImport } from './routes/(authed)/team'
import { Route as authedSecurityRouteImport } from './routes/(authed)/security'
import { Route as authedProjectsRouteImport } from './routes/(authed)/projects'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const authedRouteRoute = authedRouteRouteImport.update({
  id: '/(authed)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authedTeamRoute = authedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedSecurityRoute = authedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedProjectsRoute = authedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => authedRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/projects': typeof authedProjectsRoute
  '/security': typeof authedSecurityRoute
  '/team': typeof authedTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/projects': typeof authedProjectsRoute
  '/security': typeof authedSecurityRoute
  '/team': typeof authedTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(authed)': typeof authedRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(authed)/projects': typeof authedProjectsRoute
  '/(authed)/security': typeof authedSecurityRoute
  '/(authed)/team': typeof authedTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/projects' | '/security' | '/team'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/projects' | '/security' | '/team'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(authed)'
    | '/(auth)/login'
    | '/(authed)/projects'
    | '/(authed)/security'
    | '/(authed)/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  authedRouteRoute: typeof authedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authed)': {
      id: '/(authed)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/team': {
      id: '/(authed)/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof authedTeamRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/security': {
      id: '/(authed)/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof authedSecurityRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/projects': {
      id: '/(authed)/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof authedProjectsRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface authedRouteRouteChildren {
  authedProjectsRoute: typeof authedProjectsRoute
  authedSecurityRoute: typeof authedSecurityRoute
  authedTeamRoute: typeof authedTeamRoute
}

const authedRouteRouteChildren: authedRouteRouteChildren = {
  authedProjectsRoute: authedProjectsRoute,
  authedSecurityRoute: authedSecurityRoute,
  authedTeamRoute: authedTeamRoute,
}

const authedRouteRouteWithChildren = authedRouteRoute._addFileChildren(
  authedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  authedRouteRoute: authedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
