/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authedRouteRouteImport } from './routes/(authed)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authedTeamRouteImport } from './routes/(authed)/team'
import { Route as authedSecurityRouteImport } from './routes/(authed)/security'
import { Route as authMagicRouteImport } from './routes/(auth)/magic'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authedProjectsIndexRouteImport } from './routes/(authed)/projects/index'
import { Route as authedProjectsSlugRouteImport } from './routes/(authed)/projects/$slug'
import { Route as authInvitesTokenRouteImport } from './routes/(auth)/invites.$token'
import { Route as authedProjectsSlugLlmRouteImport } from './routes/(authed)/projects/$slug.llm'

const authedRouteRoute = authedRouteRouteImport.update({
  id: '/(authed)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authedTeamRoute = authedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedSecurityRoute = authedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => authedRouteRoute,
} as any)
const authMagicRoute = authMagicRouteImport.update({
  id: '/magic',
  path: '/magic',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authedProjectsIndexRoute = authedProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedProjectsSlugRoute = authedProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => authedRouteRoute,
} as any)
const authInvitesTokenRoute = authInvitesTokenRouteImport.update({
  id: '/invites/$token',
  path: '/invites/$token',
  getParentRoute: () => authRouteRoute,
} as any)
const authedProjectsSlugLlmRoute = authedProjectsSlugLlmRouteImport.update({
  id: '/llm',
  path: '/llm',
  getParentRoute: () => authedProjectsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/magic': typeof authMagicRoute
  '/security': typeof authedSecurityRoute
  '/team': typeof authedTeamRoute
  '/invites/$token': typeof authInvitesTokenRoute
  '/projects/$slug': typeof authedProjectsSlugRouteWithChildren
  '/projects/': typeof authedProjectsIndexRoute
  '/projects/$slug/llm': typeof authedProjectsSlugLlmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/magic': typeof authMagicRoute
  '/security': typeof authedSecurityRoute
  '/team': typeof authedTeamRoute
  '/invites/$token': typeof authInvitesTokenRoute
  '/projects/$slug': typeof authedProjectsSlugRouteWithChildren
  '/projects': typeof authedProjectsIndexRoute
  '/projects/$slug/llm': typeof authedProjectsSlugLlmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(authed)': typeof authedRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/magic': typeof authMagicRoute
  '/(authed)/security': typeof authedSecurityRoute
  '/(authed)/team': typeof authedTeamRoute
  '/(auth)/invites/$token': typeof authInvitesTokenRoute
  '/(authed)/projects/$slug': typeof authedProjectsSlugRouteWithChildren
  '/(authed)/projects/': typeof authedProjectsIndexRoute
  '/(authed)/projects/$slug/llm': typeof authedProjectsSlugLlmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/magic'
    | '/security'
    | '/team'
    | '/invites/$token'
    | '/projects/$slug'
    | '/projects/'
    | '/projects/$slug/llm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/magic'
    | '/security'
    | '/team'
    | '/invites/$token'
    | '/projects/$slug'
    | '/projects'
    | '/projects/$slug/llm'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(authed)'
    | '/(auth)/login'
    | '/(auth)/magic'
    | '/(authed)/security'
    | '/(authed)/team'
    | '/(auth)/invites/$token'
    | '/(authed)/projects/$slug'
    | '/(authed)/projects/'
    | '/(authed)/projects/$slug/llm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  authedRouteRoute: typeof authedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authed)': {
      id: '/(authed)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/team': {
      id: '/(authed)/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof authedTeamRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/security': {
      id: '/(authed)/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof authedSecurityRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(auth)/magic': {
      id: '/(auth)/magic'
      path: '/magic'
      fullPath: '/magic'
      preLoaderRoute: typeof authMagicRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(authed)/projects/': {
      id: '/(authed)/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof authedProjectsIndexRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/projects/$slug': {
      id: '/(authed)/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof authedProjectsSlugRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(auth)/invites/$token': {
      id: '/(auth)/invites/$token'
      path: '/invites/$token'
      fullPath: '/invites/$token'
      preLoaderRoute: typeof authInvitesTokenRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(authed)/projects/$slug/llm': {
      id: '/(authed)/projects/$slug/llm'
      path: '/llm'
      fullPath: '/projects/$slug/llm'
      preLoaderRoute: typeof authedProjectsSlugLlmRouteImport
      parentRoute: typeof authedProjectsSlugRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authMagicRoute: typeof authMagicRoute
  authInvitesTokenRoute: typeof authInvitesTokenRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authMagicRoute: authMagicRoute,
  authInvitesTokenRoute: authInvitesTokenRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface authedProjectsSlugRouteChildren {
  authedProjectsSlugLlmRoute: typeof authedProjectsSlugLlmRoute
}

const authedProjectsSlugRouteChildren: authedProjectsSlugRouteChildren = {
  authedProjectsSlugLlmRoute: authedProjectsSlugLlmRoute,
}

const authedProjectsSlugRouteWithChildren =
  authedProjectsSlugRoute._addFileChildren(authedProjectsSlugRouteChildren)

interface authedRouteRouteChildren {
  authedSecurityRoute: typeof authedSecurityRoute
  authedTeamRoute: typeof authedTeamRoute
  authedProjectsSlugRoute: typeof authedProjectsSlugRouteWithChildren
  authedProjectsIndexRoute: typeof authedProjectsIndexRoute
}

const authedRouteRouteChildren: authedRouteRouteChildren = {
  authedSecurityRoute: authedSecurityRoute,
  authedTeamRoute: authedTeamRoute,
  authedProjectsSlugRoute: authedProjectsSlugRouteWithChildren,
  authedProjectsIndexRoute: authedProjectsIndexRoute,
}

const authedRouteRouteWithChildren = authedRouteRoute._addFileChildren(
  authedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  authedRouteRoute: authedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
