"""Atomic ``.env`` writer.

The repo's ``.env`` file is the bridge between Docker Compose and the
running services. The DB is the source of truth, but
``docker compose up`` reads from the file — so on every UI-driven
change we regenerate it from ``instance_config``, write to a temp
file in the same directory, ``fsync``, and ``os.replace`` (atomic on
POSIX). If the subsequent restart fails, callers can roll back by
calling ``write_atomic`` again with the previous content.

The orchestrator does not own *all* env vars — only the ones the
dashboard manages. Operator-set keys (``FEEDBOT_SECRET_KEY``,
``DATABASE_URL``, ``FEEDBOT_BOT_TOKEN``, etc.) are preserved
verbatim by reading them from the existing file before rewriting.
"""

from __future__ import annotations

import contextlib
import logging
import os
import tempfile
from collections.abc import Mapping
from pathlib import Path

from feedbot_api.orchestrator.settings import InstanceSettings

log = logging.getLogger("feedbot.orchestrator.env")


# Keys whose values are owned by the orchestrator (sourced from
# ``instance_config``). Anything not in this set is preserved as-is
# from the existing ``.env`` file.
_MANAGED_KEYS: frozenset[str] = frozenset(
    {
        "EMAIL_BACKEND",
        "SMTP_HOST",
        "SMTP_PORT",
        "SMTP_USER",
        "SMTP_PASSWORD",
        "SMTP_FROM",
        "TELEGRAM_BOT_TOKEN",
        "FEEDBOT_TELEGRAM_BOT_USERNAME",
    }
)


def default_env_path() -> Path:
    """Resolve the ``.env`` location.

    ``FEEDBOT_ENV_FILE`` overrides for tests and non-standard
    layouts; otherwise we look for ``.env`` next to the
    ``docker-compose.yml`` (i.e. the repo root) using
    ``FEEDBOT_WORKDIR`` as the anchor, falling back to the current
    working directory.
    """
    override = os.getenv("FEEDBOT_ENV_FILE")
    if override:
        return Path(override)
    workdir = os.getenv("FEEDBOT_WORKDIR")
    base = Path(workdir) if workdir else Path.cwd()
    return base / ".env"


def parse(text: str) -> dict[str, str]:
    """Parse a ``.env`` file body into a key/value dict.

    Format is the docker-compose flavour: ``KEY=value`` per line,
    ``#`` comments and blank lines are skipped, surrounding single or
    double quotes are stripped, no shell expansion. We intentionally
    do not preserve comments — when we rewrite, we rewrite the whole
    thing from a generated header.
    """
    out: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
            value = value[1:-1]
        out[key] = value
    return out


def render(values: Mapping[str, str]) -> str:
    """Render a dict back to ``.env`` text.

    Stable ordering (managed keys first, then preserved keys, both
    alphabetical) so ``git diff`` on a checked-in template stays
    readable. Values that contain spaces, ``#`` or ``"`` are
    double-quoted.
    """
    header = (
        "# ─────────────────────────────────────────────────────────────\n"
        "# Auto-generated by Feedbot orchestrator. Edit via the dashboard\n"
        "# Settings page — manual changes to managed keys will be lost on\n"
        "# the next config save.\n"
        "# ─────────────────────────────────────────────────────────────\n"
    )

    def _emit(key: str) -> str:
        v = values[key]
        if any(c in v for c in (" ", "\t", "#", '"')):
            escaped = v.replace("\\", "\\\\").replace('"', '\\"')
            return f'{key}="{escaped}"'
        return f"{key}={v}"

    managed = sorted(k for k in values if k in _MANAGED_KEYS)
    preserved = sorted(k for k in values if k not in _MANAGED_KEYS)
    lines = [header.rstrip()]
    if managed:
        lines.append("")
        lines.append("# ── Managed by orchestrator ─────────────────────")
        lines.extend(_emit(k) for k in managed)
    if preserved:
        lines.append("")
        lines.append("# ── Operator-managed (preserved on save) ────────")
        lines.extend(_emit(k) for k in preserved)
    lines.append("")
    return "\n".join(lines)


def project(settings: InstanceSettings) -> dict[str, str]:
    """Project decrypted ``InstanceSettings`` onto the managed env keys.

    Empty / unset values are emitted as ``KEY=`` so docker-compose
    interprets them as the empty string (matching the
    ``${SMTP_HOST:-}`` defaults) rather than inheriting a stale shell
    value.
    """
    smtp_configured = settings.smtp.is_configured
    return {
        # Keep EMAIL_BACKEND consistent with whether SMTP is wired up.
        # If the owner clears SMTP credentials we fall back to the
        # console backend; the API guards against that on production
        # URLs at startup, surfacing a 500 with a useful log.
        "EMAIL_BACKEND": "smtp" if smtp_configured else "console",
        "SMTP_HOST": settings.smtp.host or "",
        "SMTP_PORT": str(settings.smtp.port) if settings.smtp.port else "",
        "SMTP_USER": settings.smtp.user or "",
        "SMTP_PASSWORD": settings.smtp.password or "",
        "SMTP_FROM": settings.smtp.sender or "",
        "TELEGRAM_BOT_TOKEN": settings.bot.token or "",
        "FEEDBOT_TELEGRAM_BOT_USERNAME": settings.bot.username or "",
    }


def merge(existing: Mapping[str, str], managed: Mapping[str, str]) -> dict[str, str]:
    """Combine existing operator keys with freshly-projected managed keys.

    Operator keys win for everything *not* in ``_MANAGED_KEYS``. The
    managed projection wins for managed keys (so clearing SMTP in the
    UI actually clears it on disk).
    """
    merged = {k: v for k, v in existing.items() if k not in _MANAGED_KEYS}
    merged.update(managed)
    return merged


def write_atomic(path: Path, text: str) -> None:
    """Write ``text`` to ``path`` via temp-file + rename.

    The temp file is created in the same directory so ``os.replace``
    is a same-filesystem rename (atomic on POSIX). Mode is set to
    ``0600`` since the file holds plaintext SMTP / bot credentials
    that the API needs at process boot.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(
        prefix=".env.", suffix=".tmp", dir=str(path.parent)
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(text)
            f.flush()
            os.fsync(f.fileno())
        os.chmod(tmp_name, 0o600)
        os.replace(tmp_name, path)
    except Exception:
        # Don't leave a stray ``.env.<rand>.tmp`` behind on failure.
        with contextlib.suppress(FileNotFoundError):
            os.unlink(tmp_name)
        raise


def read_existing(path: Path) -> dict[str, str]:
    """Read + parse ``path``; return ``{}`` if it doesn't exist yet."""
    try:
        return parse(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return {}


def regenerate(settings: InstanceSettings, *, path: Path | None = None) -> str:
    """Top-level entry: rewrite the env file from the given settings.

    Returns the rendered text (also useful for tests / dry-run UIs).
    Raises whatever the underlying filesystem error is — callers are
    expected to catch and roll back the DB transaction.
    """
    target = path or default_env_path()
    existing = read_existing(target)
    merged = merge(existing, project(settings))
    text = render(merged)
    write_atomic(target, text)
    log.info("orchestrator rewrote %s (%d keys)", target, len(merged))
    return text
