"""Tests for the orchestrator module.

Covers the pure pieces that don't touch the host:

- ``env.parse`` / ``env.render`` round-trip + atomic write.
- ``env.regenerate`` projects ``InstanceSettings`` onto managed keys
  and preserves operator-managed keys.
- ``settings.load`` decrypts Fernet-encrypted columns and
  gracefully falls back when ciphertext is unreadable.
- ``audit.redact`` strips secret values from event payloads.
- ``caddy.build_*_config`` produces well-formed JSON with the
  expected structure (no live admin API call).
- ``autostart.status`` reports the right platform and never
  touches systemctl / launchctl in dry mode.
- ``Orchestrator.apply_email`` end-to-end with compose + env
  monkeypatched so we don't shell out.
"""

from __future__ import annotations

from pathlib import Path
from unittest.mock import AsyncMock

import pytest
from feedbot_api.orchestrator import Orchestrator, audit, autostart, caddy, compose, env, settings
from feedbot_core.llm.crypto import encrypt_key
from feedbot_core.repos import update_instance_config


# ── env ─────────────────────────────────────────────────────────────


def test_env_parse_handles_quotes_and_comments():
    text = """
# top comment
KEY1=plain
KEY2="quoted value"
KEY3='single quoted'
# inline=ignored
KEY4=
"""
    parsed = env.parse(text)
    assert parsed == {
        "KEY1": "plain",
        "KEY2": "quoted value",
        "KEY3": "single quoted",
        "KEY4": "",
    }


def test_env_render_round_trip():
    values = {
        "SMTP_HOST": "smtp.example.com",
        "SMTP_PORT": "587",
        "FEEDBOT_SECRET_KEY": "abc",
    }
    rendered = env.render(values)
    # Header is present, all keys round-trip back through parse.
    assert "Auto-generated by Feedbot orchestrator" in rendered
    assert env.parse(rendered) == values


def test_env_render_quotes_values_with_spaces():
    rendered = env.render({"SMTP_FROM": "Feedbot <noreply@example.com>"})
    assert 'SMTP_FROM="Feedbot <noreply@example.com>"' in rendered
    assert env.parse(rendered)["SMTP_FROM"] == "Feedbot <noreply@example.com>"


def test_env_write_atomic_creates_file_and_overwrites(tmp_path: Path):
    target = tmp_path / ".env"
    env.write_atomic(target, "KEY=v1\n")
    assert target.read_text() == "KEY=v1\n"
    env.write_atomic(target, "KEY=v2\n")
    assert target.read_text() == "KEY=v2\n"
    # No leftover temp files in the same dir.
    leftovers = [p for p in tmp_path.iterdir() if p.name.startswith(".env.")]
    assert leftovers == []


def test_env_regenerate_preserves_operator_keys(tmp_path: Path):
    target = tmp_path / ".env"
    target.write_text(
        "FEEDBOT_SECRET_KEY=keep-me\n"
        "DATABASE_URL=postgresql://x\n"
        "SMTP_HOST=stale-host\n",  # managed key — should be overwritten
        encoding="utf-8",
    )
    s = settings.InstanceSettings(
        smtp=settings.SmtpConfig(
            host="smtp.new", port=587, user="u", password="p", sender="s@x"
        ),
        bot=settings.BotConfig(token=None, username=None),
        proxy=settings.ProxyConfig(domain=None, https_enabled=False, letsencrypt_email=None),
        system=settings.SystemConfig(autostart_enabled=False, telemetry_enabled=False),
    )
    env.regenerate(s, path=target)

    parsed = env.parse(target.read_text())
    # Managed keys reflect the new settings.
    assert parsed["SMTP_HOST"] == "smtp.new"
    assert parsed["SMTP_PASSWORD"] == "p"
    assert parsed["EMAIL_BACKEND"] == "smtp"
    # Operator keys are preserved verbatim.
    assert parsed["FEEDBOT_SECRET_KEY"] == "keep-me"
    assert parsed["DATABASE_URL"] == "postgresql://x"


def test_env_regenerate_clears_email_backend_when_smtp_unset(tmp_path: Path):
    target = tmp_path / ".env"
    s = settings.InstanceSettings(
        smtp=settings.SmtpConfig(host=None, port=None, user=None, password=None, sender=None),
        bot=settings.BotConfig(token=None, username=None),
        proxy=settings.ProxyConfig(domain=None, https_enabled=False, letsencrypt_email=None),
        system=settings.SystemConfig(autostart_enabled=False, telemetry_enabled=False),
    )
    env.regenerate(s, path=target)
    parsed = env.parse(target.read_text())
    assert parsed["EMAIL_BACKEND"] == "console"
    assert parsed["SMTP_HOST"] == ""


# ── settings ────────────────────────────────────────────────────────


@pytest.mark.asyncio
async def test_settings_load_decrypts_secrets(db_session):
    # Seed the singleton with encrypted secrets via the repo.
    await update_instance_config(
        db_session,
        smtp_host="smtp.x",
        smtp_port=587,
        smtp_user="u",
        smtp_password_encrypted=encrypt_key("plain-pw"),
        smtp_from="from@x",
        telegram_bot_token_encrypted=encrypt_key("123:abc"),
        telegram_bot_username="mybot",
    )
    s = await settings.load(db_session)
    assert s.smtp.password == "plain-pw"
    assert s.smtp.is_configured
    assert s.bot.token == "123:abc"
    assert s.bot.username == "mybot"


@pytest.mark.asyncio
async def test_settings_load_tolerates_unreadable_ciphertext(db_session):
    # Garbage that isn't a Fernet token. ``_safe_decrypt`` should
    # swallow it and return ``None`` so the settings page still loads.
    await update_instance_config(
        db_session,
        smtp_password_encrypted=b"not-fernet",
    )
    s = await settings.load(db_session)
    assert s.smtp.password is None


# ── audit ───────────────────────────────────────────────────────────


def test_audit_redact_hides_secret_fields():
    out = audit.redact(
        {
            "smtp_host": "x",
            "smtp_password": "supersecret",
            "telegram_bot_token": "123:abc",
            "domain": "example.com",
        }
    )
    assert out["smtp_host"] == "x"
    assert out["smtp_password"] == "<redacted>"
    assert out["telegram_bot_token"] == "<redacted>"
    assert out["domain"] == "example.com"


@pytest.mark.asyncio
async def test_audit_config_changed_emits_event_with_redaction(db_session):
    await audit.config_changed(
        db_session,
        user_id=None,
        tenant_id=None,
        section="email",
        fields={"smtp_host": "smtp.x", "smtp_password": "secret"},
    )
    from feedbot_core.models import AuditEvent
    from sqlalchemy import select

    rows = (await db_session.execute(select(AuditEvent))).scalars().all()
    assert len(rows) == 1
    assert rows[0].event == "admin.config.changed"
    assert "secret" not in (rows[0].details or "")
    assert "<redacted>" in (rows[0].details or "")


# ── caddy ───────────────────────────────────────────────────────────


def test_caddy_ip_only_config_disables_auto_https():
    cfg = caddy.build_ip_only_config()
    server = cfg["apps"]["http"]["servers"]["feedbot"]
    assert server["listen"] == [":80"]
    assert server["automatic_https"] == {"disable": True}
    # The 4 routes: /api, /mcp, /healthz, fallback.
    assert len(server["routes"]) == 4


def test_caddy_domain_config_has_acme_issuer():
    cfg = caddy.build_domain_config(
        domain="feedbot.example.com", letsencrypt_email="ops@example.com"
    )
    policies = cfg["apps"]["tls"]["automation"]["policies"]
    assert policies[0]["subjects"] == ["feedbot.example.com"]
    assert policies[0]["issuers"][0]["module"] == "acme"
    assert policies[0]["issuers"][0]["email"] == "ops@example.com"
    # Both servers (443 + 80 redirect) present.
    assert set(cfg["apps"]["http"]["servers"]) == {"feedbot", "redirect"}


def test_caddy_domain_config_rejects_url_in_domain():
    with pytest.raises(ValueError):
        caddy.build_domain_config(
            domain="https://feedbot.example.com",
            letsencrypt_email="ops@example.com",
        )


def test_caddy_domain_config_requires_email():
    with pytest.raises(ValueError):
        caddy.build_domain_config(
            domain="feedbot.example.com", letsencrypt_email=""
        )


# ── autostart ───────────────────────────────────────────────────────


def test_autostart_status_returns_disabled_on_fresh_box(monkeypatch, tmp_path: Path):
    # Force a non-existent unit path so ``status`` reports disabled.
    monkeypatch.setattr(autostart, "_systemd_unit_path", lambda: tmp_path / "missing.service")
    monkeypatch.setattr(autostart, "_launchd_plist_path", lambda: tmp_path / "missing.plist")
    s = autostart.status()
    assert s.enabled is False


def test_autostart_unit_body_includes_workdir(monkeypatch, tmp_path: Path):
    monkeypatch.setenv("FEEDBOT_WORKDIR", str(tmp_path))
    body = autostart._systemd_unit_body()
    assert f"WorkingDirectory={tmp_path}" in body
    assert "compose up -d" in body


# ── Orchestrator end-to-end (compose + env mocked) ──────────────────


@pytest.mark.asyncio
async def test_orchestrator_apply_email_writes_env_and_restarts(
    db_session, tmp_path, monkeypatch
):
    target = tmp_path / ".env"
    monkeypatch.setenv("FEEDBOT_ENV_FILE", str(target))

    restart_mock = AsyncMock()
    monkeypatch.setattr(compose, "restart", restart_mock)

    orch = Orchestrator(db_session, user_id=None)
    result = await orch.apply_email(
        host="smtp.x",
        port=587,
        user="u",
        password="pw",
        sender="from@x",
    )

    assert result.smtp.password == "pw"
    assert target.exists()
    parsed = env.parse(target.read_text())
    assert parsed["SMTP_HOST"] == "smtp.x"
    assert parsed["SMTP_PASSWORD"] == "pw"
    restart_mock.assert_awaited_once_with("api")

    # Audit row was written with redacted password.
    from feedbot_core.models import AuditEvent
    from sqlalchemy import select

    events = (
        await db_session.execute(
            select(AuditEvent).where(AuditEvent.event == "admin.config.changed")
        )
    ).scalars().all()
    assert events
    assert "pw" not in (events[-1].details or "")


@pytest.mark.asyncio
async def test_orchestrator_apply_proxy_calls_caddy(db_session, tmp_path, monkeypatch):
    monkeypatch.setenv("FEEDBOT_ENV_FILE", str(tmp_path / ".env"))
    apply_mock = AsyncMock()
    monkeypatch.setattr(caddy, "apply_domain", apply_mock)

    orch = Orchestrator(db_session, user_id=None)
    result = await orch.apply_proxy(
        domain="feedbot.example.com", letsencrypt_email="ops@example.com"
    )

    apply_mock.assert_awaited_once_with(
        domain="feedbot.example.com", letsencrypt_email="ops@example.com"
    )
    assert result.proxy.domain == "feedbot.example.com"
    assert result.proxy.https_enabled is True
