/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/feedbacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List */
        get: operations["list__v1_feedbacks_get"];
        put?: never;
        /** Create */
        post: operations["create__v1_feedbacks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feedbacks/{public_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: operations["get__v1_feedbacks__public_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch */
        patch: operations["patch__v1_feedbacks__public_id__patch"];
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats__v1_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a magic-link sign-in email
         * @description Send a magic-link to ``body.email``.
         *
         *     Always responds 200 with ``{"sent": true}`` — whether the email is
         *     registered or not is intentionally hidden to prevent enumeration.
         *
         *     On every call (registered or not) the response sets an ``mlnonce``
         *     cookie. The link the user clicks must be opened in the same browser
         *     or the magic-link verifier will mark the login as ``cross_device``
         *     and email a notice.
         */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/magic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consume a magic-link token and start a session
         * @description Consume a magic-link and issue a server-side session cookie.
         *
         *     On success, sets the ``fb_session`` cookie and clears ``mlnonce``.
         *     The SPA should treat any 2xx response as "logged in" and refetch
         *     ``/v1/me`` to load identity.
         */
        get: operations["magic_v1_auth_magic_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the current session
         * @description Revoke just the session that authenticated this request and clear the cookie.
         *
         *     Idempotent — returns 204 even if no cookie was sent.
         */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke every session of the current user
         * @description Revoke every active session of ``me`` (including the one making the request).
         *
         *     Useful for "Sign out everywhere" on the future Security page.
         */
        post: operations["logout_all_v1_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active sessions for the current user */
        get: operations["list_sessions_v1_auth_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Identity + visible projects for the current user
         * @description Everything the SPA needs at boot: identity, role, tenant, projects.
         *
         *     A 401 here tells the SPA to redirect the user to the login screen.
         */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/setup-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whether the deployment still needs first-run bootstrap
         * @description Cheap check the SPA does at boot to decide whether to route the user
         *     to ``/setup`` or to ``/login``.
         *
         *     No auth — there's no user yet when this matters, and post-bootstrap the
         *     answer is a stable ``False``.
         */
        get: operations["setup_status_v1_setup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bootstrap the first owner — only valid while the users table is empty
         * @description Create the first tenant + owner user, then email them a magic link.
         *
         *     On deployments without working SMTP we fall back to returning the link
         *     inline — the SPA renders it as a one-time button so the new owner can
         *     finish onboarding without having to dig through container logs.
         */
        post: operations["setup_bootstrap_v1_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects visible to the current user
         * @description Owner/admin sees every project in the tenant; members see only their own.
         */
        get: operations["list_projects_v1_projects_get"];
        put?: never;
        /** Create a new project (admin/owner only) */
        post: operations["create_project__v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a project's detail (with feedback counts) */
        get: operations["get_project_v1_projects__slug__get"];
        put?: never;
        post?: never;
        /** Delete a project and all its data (admin/owner only) */
        delete: operations["delete_project__v1_projects__slug__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API keys for a project (admin only) */
        get: operations["list_keys_v1_projects__slug__api_keys_get"];
        put?: never;
        /** Issue a new API key — secret is shown ONCE (admin only) */
        post: operations["create_key_v1_projects__slug__api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}/api-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API key (admin only). Idempotent. */
        delete: operations["revoke_key_v1_projects__slug__api_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}/chat-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List chat links for a project */
        get: operations["get_chat_links_v1_projects__slug__chat_links_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}/chat-link-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a 15-min deep-link token to bind a Telegram chat to this project (admin only) */
        post: operations["create_chat_link_token_v1_projects__slug__chat_link_tokens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}/chat-links/{link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect a chat from this project (admin only) */
        delete: operations["delete_chat_link_v1_projects__slug__chat_links__link_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}/feedbacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List feedback in a project (filterable) */
        get: operations["list__v1_projects__slug__feedbacks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}/feedbacks/{public_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one feedback by FB-XXXXXX */
        get: operations["get__v1_projects__slug__feedbacks__public_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update status / append a note / queue a reply */
        patch: operations["patch__v1_projects__slug__feedbacks__public_id__patch"];
        trace?: never;
    };
    "/v1/projects/{slug}/feedbacks-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Counts grouped by status (cookie-authed) */
        get: operations["stats__v1_projects__slug__feedbacks_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/llm/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available LLM providers (from the registry)
         * @description The SPA reads this to populate the provider/model dropdowns. Adding a
         *     new provider in ``feedbot_core/llm/providers/`` makes it appear here
         *     automatically — no UI change required.
         */
        get: operations["get_providers_v1_llm_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}/llm-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read LLM settings for a project (admin only). The key is never returned. */
        get: operations["get_llm_settings_v1_projects__slug__llm_settings_get"];
        /** Update LLM settings (admin only). See module docstring for api_key semantics. */
        put: operations["put_llm_settings_v1_projects__slug__llm_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}/llm-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a single classification round-trip and record the outcome (admin only)
         * @description Round-trip a fixed sample feedback through the configured provider.
         *
         *     Always returns 200 with a structured outcome — even when the provider
         *     rejects the request. The error_text on the response is truncated; the
         *     same truncated value is persisted in ``last_test_error``.
         */
        post: operations["llm_test_v1_projects__slug__llm_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}/llm-calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent LLM calls for the audit table (admin only) */
        get: operations["list_llm_calls_v1_projects__slug__llm_calls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenant/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every user in the tenant (admin/owner only) */
        get: operations["list_tenant_users__v1_tenant_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenant/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a user from the tenant (admin/owner only) */
        delete: operations["delete_tenant_user_v1_tenant_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Change a user's role within the tenant (admin/owner only) */
        patch: operations["patch_tenant_user_v1_tenant_users__user_id__patch"];
        trace?: never;
    };
    "/v1/tenant/transfer-ownership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Owner-only: hand the role to another admin in the same tenant */
        post: operations["transfer_ownership_v1_tenant_transfer_ownership_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pending invites for this tenant (admin/owner only) */
        get: operations["list_invites_v1_invites_get"];
        put?: never;
        /** Create an invite + send the email (admin/owner only) */
        post: operations["create_invite_v1_invites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invites/{invite_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a pending invite (admin/owner only) */
        delete: operations["delete_invite_v1_invites__invite_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invites/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview an invite (no auth) — used by the SPA's accept page
         * @description Open endpoint: anyone with the token can read the invite metadata. We
         *     deliberately surface only what's needed to render the accept screen
         *     (workspace name, email, role, project name, expiry) — never the inviter's
         *     email or anything that would help enumerate the tenant.
         */
        get: operations["preview_invite_v1_invites_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invites/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept an invite (no auth) — creates the user and starts a session */
        post: operations["accept_invite_v1_invites_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members of a project (admin only) */
        get: operations["list_members_v1_projects__slug__members_get"];
        put?: never;
        /** Add an existing tenant user to this project (admin only) */
        post: operations["add_member_v1_projects__slug__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{slug}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member from this project (admin only) */
        delete: operations["remove_member_v1_projects__slug__members__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/internal/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest */
        post: operations["ingest_v1_internal_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/internal/redeem-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeem Link */
        post: operations["redeem_link_v1_internal_redeem_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/internal/ingest-reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Reply
         * @description The user replied (in chat) to one of our outbound messages.
         *
         *     The bot detects 'this Telegram message is a reply to one we sent' and posts
         *     here. We resolve which feedback owns that outbound message_id and record
         *     the body as user_reply, flipping status back to 'triaged' so Claude (or a
         *     human) sees it on the next read.
         */
        post: operations["ingest_reply_v1_internal_ingest_reply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/internal/outbound-pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Outbound Pending
         * @description The bot polls this every few seconds and delivers each item to chat.
         *
         *     Two kinds of outbound messages live in the same queue: queued replies (the
         *     team or Claude wrote in `reply_to_user`) and done notifications (status
         *     just flipped to `done`). Both are delivered to the same chat where the
         *     feedback was first reported, so the conversation stays in one thread.
         */
        get: operations["outbound_pending_v1_internal_outbound_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/internal/outbound-ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Outbound Ack
         * @description The bot confirms it delivered (or failed to deliver) an outbound message.
         */
        post: operations["outbound_ack_v1_internal_outbound_ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiKeyCreated
         * @description Response from ``POST /v1/projects/{slug}/api-keys``.
         *
         *     ``key`` is the **only** time the secret is exposed. Store it now or rotate.
         */
        ApiKeyCreated: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /**
             * Prefix
             * @description First 12 chars of the key, e.g. 'fbk_live_AbCdEf12'.
             */
            prefix: string;
            /**
             * Scope
             * @description read | write | admin
             */
            scope: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
            /**
             * Key
             * @description Full secret (fbk_*); shown once, never re-rendered.
             */
            key: string;
        };
        /**
         * ApiKeyIn
         * @description Body for ``POST /v1/projects/{slug}/api-keys``.
         */
        ApiKeyIn: {
            /** Label */
            label: string;
            /**
             * Scope
             * @default write
             */
            scope: string;
        };
        /**
         * ApiKeyOut
         * @description List/get view of an API key. The secret is never re-rendered.
         */
        ApiKeyOut: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /**
             * Prefix
             * @description First 12 chars of the key, e.g. 'fbk_live_AbCdEf12'.
             */
            prefix: string;
            /**
             * Scope
             * @description read | write | admin
             */
            scope: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
        };
        /** ChatLinkOut */
        ChatLinkOut: {
            /** Id */
            id: number;
            /** Platform */
            platform: string;
            /** Chat Id */
            chat_id: string;
            /** Title */
            title: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ChatLinkTokenOut
         * @description Response from ``POST /v1/projects/{slug}/chat-link-tokens``.
         *
         *     ``deep_link`` is empty when ``FEEDBOT_TELEGRAM_BOT_USERNAME`` is unset on
         *     the deployment; the SPA hides the "Open Telegram" button in that case.
         */
        ChatLinkTokenOut: {
            /** Token */
            token: string;
            /** Deep Link */
            deep_link: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** FeedbackIn */
        FeedbackIn: {
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** @default other */
            type: components["schemas"]["FeedbackType"];
            /** @default medium */
            severity: components["schemas"]["Severity"];
            /**
             * Author Platform
             * @default web
             */
            author_platform: string;
            /**
             * Author Id
             * @default
             */
            author_id: string;
            /** Author Name */
            author_name?: string | null;
        };
        /** FeedbackOut */
        FeedbackOut: {
            /** Id */
            id: string;
            /** Project Slug */
            project_slug: string;
            type: components["schemas"]["FeedbackType"];
            severity: components["schemas"]["Severity"];
            status: components["schemas"]["FeedbackStatus"];
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Summary */
            summary: string | null;
            /** Tags */
            tags: string | null;
            /** Author Platform */
            author_platform: string;
            /** Author Name */
            author_name: string | null;
            /** Note */
            note: string | null;
            /** Reply To User */
            reply_to_user: string | null;
            /** User Reply */
            user_reply: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** FeedbackPatch */
        FeedbackPatch: {
            status?: components["schemas"]["FeedbackStatus"] | null;
            /** Note */
            note?: string | null;
            /** Reply To User */
            reply_to_user?: string | null;
        };
        /**
         * FeedbackStatus
         * @enum {string}
         */
        FeedbackStatus: "new" | "triaged" | "in_progress" | "done" | "wont_fix";
        /**
         * FeedbackType
         * @enum {string}
         */
        FeedbackType: "bug" | "feature" | "question" | "other";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestIn */
        IngestIn: {
            /** Platform */
            platform: string;
            /** Chat Id */
            chat_id: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** @default other */
            type: components["schemas"]["FeedbackType"];
            /** @default medium */
            severity: components["schemas"]["Severity"];
            /** Author Id */
            author_id: string;
            /** Author Name */
            author_name?: string | null;
        };
        /**
         * IngestReplyIn
         * @description Inbound reply from a user — they replied to one of our outbound messages.
         */
        IngestReplyIn: {
            /** Platform */
            platform: string;
            /** Chat Id */
            chat_id: string;
            /** Replied To Message Id */
            replied_to_message_id: string;
            /** Body */
            body: string;
            /** Author Id */
            author_id: string;
            /** Author Name */
            author_name?: string | null;
        };
        /** InviteAcceptIn */
        InviteAcceptIn: {
            /** Token */
            token: string;
        };
        /** InviteIn */
        InviteIn: {
            /** Email */
            email: string;
            /**
             * Role
             * @default member
             */
            role: string;
            /** Project Slug */
            project_slug?: string | null;
        };
        /** InviteOut */
        InviteOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Project Slug */
            project_slug: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Used At */
            used_at: string | null;
            /** Invited By Email */
            invited_by_email: string | null;
        };
        /**
         * InvitePreviewOut
         * @description Response from ``GET /v1/invites/preview?token=...`` — no auth required.
         *
         *     Designed so the SPA's "Accept invite" page can show context (workspace name,
         *     email, role) before the user clicks "Accept". Returns 404 for any invalid
         *     state; never reveals whether the email exists in another tenant.
         */
        InvitePreviewOut: {
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Tenant Name */
            tenant_name: string;
            /** Project Name */
            project_name: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * LLMCallOut
         * @description One row from ``GET /v1/projects/{slug}/llm-calls``. Used for the audit table.
         */
        LLMCallOut: {
            /** Id */
            id: number;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Purpose */
            purpose: string;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Total Tokens */
            total_tokens: number;
            /** Usd Cost */
            usd_cost: number;
            /** Latency Ms */
            latency_ms: number;
            /** Status */
            status: string;
            /** Error Text */
            error_text: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * LLMSettingsIn
         * @description Body for ``PUT /v1/projects/{slug}/llm-settings``.
         *
         *     Partial-update semantics:
         *       * Omit ``api_key`` to keep the existing encrypted key untouched.
         *       * Send a non-empty ``api_key`` string to set / rotate it.
         *       * Send an empty string to **clear** the key (must also set
         *         ``enabled=false`` since classification cannot run without one).
         *     The strict pattern is enforced server-side.
         */
        LLMSettingsIn: {
            /** Provider */
            provider: string;
            /** Model */
            model?: string | null;
            /**
             * Api Key
             * @description Plaintext key; encrypted server-side.
             */
            api_key?: string | null;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /** Monthly Budget Usd */
            monthly_budget_usd?: number | null;
        };
        /**
         * LLMSettingsOut
         * @description View of project LLM settings.
         *
         *     The encrypted API key is **never** included in this response. Whether one
         *     is configured is exposed only as the boolean ``has_api_key``. The provider
         *     error from the last test call (``last_test_error``) is truncated to 240
         *     characters to limit accidental key leakage if the provider echoed it back.
         */
        LLMSettingsOut: {
            /** Provider */
            provider: string;
            /** Model */
            model: string | null;
            /** Enabled */
            enabled: boolean;
            /** Monthly Budget Usd */
            monthly_budget_usd: number | null;
            /**
             * Has Api Key
             * @description True when an encrypted key is stored.
             */
            has_api_key: boolean;
            /** Last Test At */
            last_test_at: string | null;
            /** Last Test Ok */
            last_test_ok: boolean | null;
            /**
             * Last Test Error
             * @description Truncated provider error from the last /llm-test call.
             */
            last_test_error: string | null;
            /**
             * Month To Date Usd
             * @description Sum of usd_cost for this calendar month.
             */
            month_to_date_usd: number;
        };
        /**
         * LLMTestOut
         * @description Response from ``POST /v1/projects/{slug}/llm-test``.
         */
        LLMTestOut: {
            /** Ok */
            ok: boolean;
            /**
             * Status
             * @description ok | refused | error | over_budget | disabled
             */
            status: string;
            /** Provider */
            provider: string | null;
            /** Model */
            model: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Usd Cost */
            usd_cost: number;
            /**
             * Error Text
             * @description Truncated to 240 chars; never echoes back the key.
             */
            error_text: string | null;
        };
        /**
         * LoginIn
         * @description JSON body for ``POST /v1/auth/login``.
         *
         *     The SPA POSTs to this with the user's email. Same enumeration-resistant
         *     behaviour as the legacy form endpoint: response is identical whether the
         *     email exists or not.
         */
        LoginIn: {
            /** Email */
            email: string;
        };
        /**
         * LoginOut
         * @description Response from ``POST /v1/auth/login``.
         *
         *     The PKCE nonce ships back in the ``mlnonce`` cookie (httpOnly), not in
         *     this body — the SPA never sees it directly.
         */
        LoginOut: {
            /**
             * Sent
             * @description Always true; whether the email exists is intentionally hidden.
             */
            sent: boolean;
        };
        /**
         * MeOut
         * @description Response from ``GET /v1/me`` — everything the SPA needs at boot.
         */
        MeOut: {
            /**
             * User
             * @description Identity + role. Keys: id, email, role, tenant_id.
             */
            user: {
                [key: string]: unknown;
            };
            /**
             * Tenant
             * @description Workspace-level info. Keys: id, name.
             */
            tenant: {
                [key: string]: unknown;
            };
            /**
             * Projects
             * @description Projects this user can see (admins/owners: all; members: their assignments).
             */
            projects: components["schemas"]["ProjectSummary"][];
            /**
             * Is Setup Complete
             * @description False only when the database is empty (i.e. /setup is still active).
             */
            is_setup_complete: boolean;
        };
        /** OutboundAckIn */
        OutboundAckIn: {
            /** Feedback Public Id */
            feedback_public_id: string;
            /** Kind */
            kind: string;
            /** Body */
            body: string;
            /** Sent Message Id */
            sent_message_id?: string | null;
            /** Ok */
            ok: boolean;
            /** Error */
            error?: string | null;
        };
        /** OutboundItem */
        OutboundItem: {
            /** Feedback Public Id */
            feedback_public_id: string;
            /** Platform */
            platform: string;
            /** Chat Id */
            chat_id: string;
            /** Kind */
            kind: string;
            /** Body */
            body: string;
            /** Reply To Message Id */
            reply_to_message_id?: string | null;
        };
        /**
         * ProjectIn
         * @description Body for ``POST /v1/projects``.
         */
        ProjectIn: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
        };
        /** ProjectMemberAddIn */
        ProjectMemberAddIn: {
            /** User Id */
            user_id: number;
        };
        /**
         * ProjectOut
         * @description Detailed project view — superset of ``ProjectSummary``.
         */
        ProjectOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Feedback Count By Status
             * @description Counts grouped by status for the badge in the UI.
             */
            feedback_count_by_status?: {
                [key: string]: number;
            };
        };
        /**
         * ProjectSummary
         * @description Compact view of a project — used in ``/v1/me`` and listings.
         */
        ProjectSummary: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ProvidersOut
         * @description Response from ``GET /v1/llm/providers`` — populated dynamically from the
         *     feedbot_core.llm registry. The SPA uses this to render the provider/model
         *     dropdowns without hardcoding any names client-side.
         */
        ProvidersOut: {
            /**
             * Providers
             * @description Keyed by provider name; each entry has default_model + available_models.
             */
            providers: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
        };
        /** RedeemIn */
        RedeemIn: {
            /** Platform */
            platform: string;
            /** Chat Id */
            chat_id: string;
            /** Chat Title */
            chat_title?: string | null;
            /** Token */
            token: string;
        };
        /** RedeemOut */
        RedeemOut: {
            /** Project Slug */
            project_slug: string;
            /** Project Name */
            project_name: string;
        };
        /**
         * SessionOut
         * @description One row from ``GET /v1/auth/sessions``.
         *
         *     ``id`` is the full session token; sensitive — only the owner sees their
         *     own sessions, and the field is shown so the user can revoke a specific
         *     one from the future Security page.
         */
        SessionOut: {
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** User Agent */
            user_agent: string | null;
            /** Ip */
            ip: string | null;
            /**
             * Is Current
             * @description True for the session that authenticated this request.
             */
            is_current: boolean;
        };
        /**
         * SetupIn
         * @description Body for ``POST /v1/setup`` — first-run owner bootstrap.
         *
         *     Only accepted while the users table is empty; once an owner exists this
         *     endpoint returns 410 Gone. The owner gets a magic-link emailed (or, on
         *     deployments without SMTP, surfaced in the response) so they can sign in
         *     immediately.
         */
        SetupIn: {
            /** Email */
            email: string;
            /**
             * Tenant Name
             * @default
             */
            tenant_name: string;
        };
        /**
         * SetupOut
         * @description Response from ``POST /v1/setup``.
         *
         *     ``fallback_link`` is only populated when SMTP isn't configured (e.g.
         *     ``EMAIL_BACKEND=console`` in production) so the owner isn't locked out
         *     of their own instance. It's a single-use link with a 15-minute TTL; the
         *     SPA renders it as a "click here to sign in" button.
         */
        SetupOut: {
            /** Email */
            email: string;
            /**
             * Delivered
             * @description True when the magic-link email was handed off to the configured backend without raising.
             */
            delivered: boolean;
            /**
             * Fallback Link
             * @description When SMTP isn't configured, the magic link is returned here so the bootstrapping admin can copy it.
             */
            fallback_link?: string | null;
        };
        /**
         * SetupStatusOut
         * @description Response from ``GET /v1/setup-status``.
         *
         *     The SPA polls this once at boot and routes to ``/setup`` when ``required``
         *     is true. After bootstrap the endpoint reports ``required=False`` forever
         *     (until the deployment is wiped), so the SPA caches it conservatively.
         */
        SetupStatusOut: {
            /**
             * Required
             * @description True only while the users table is empty. Once an owner exists, the endpoint flips to false permanently for this DB.
             */
            required: boolean;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "low" | "medium" | "high" | "critical";
        /** StatsOut */
        StatsOut: {
            /** By Status */
            by_status: {
                [key: string]: number;
            };
            /** Total */
            total: number;
        };
        /** TenantUserOut */
        TenantUserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * TenantUserPatchIn
         * @description Body for ``PATCH /v1/tenant/users/{id}``. Only ``role`` is mutable.
         */
        TenantUserPatchIn: {
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list__v1_feedbacks_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["FeedbackStatus"] | null;
                type?: components["schemas"]["FeedbackType"] | null;
                severity?: components["schemas"]["Severity"] | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create__v1_feedbacks_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get__v1_feedbacks__public_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch__v1_feedbacks__public_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats__v1_stats_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Email delivery is not configured on this deployment. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    magic_v1_auth_magic_get: {
        parameters: {
            query: {
                email: string;
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Session created; cookie set. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or expired link. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_all_v1_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_sessions_v1_auth_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description No active session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setup_status_v1_setup_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusOut"];
                };
            };
        };
    };
    setup_bootstrap_v1_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupOut"];
                };
            };
            /** @description Setup already complete. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    create_project__v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Slug already exists in this tenant. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_v1_projects__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project__v1_projects__slug__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_keys_v1_projects__slug__api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_key_v1_projects__slug__api_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_key_v1_projects__slug__api_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                key_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Key not found in this project. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_links_v1_projects__slug__chat_links_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatLinkOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_chat_link_token_v1_projects__slug__chat_link_tokens_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatLinkTokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_chat_link_v1_projects__slug__chat_links__link_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                link_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Chat link not found in this project. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list__v1_projects__slug__feedbacks_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["FeedbackStatus"] | null;
                type?: components["schemas"]["FeedbackType"] | null;
                severity?: components["schemas"]["Severity"] | null;
                limit?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get__v1_projects__slug__feedbacks__public_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                public_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"];
                };
            };
            /** @description Feedback not in this project. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch__v1_projects__slug__feedbacks__public_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                public_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"];
                };
            };
            /** @description Feedback not in this project. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats__v1_projects__slug__feedbacks_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_providers_v1_llm_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersOut"];
                };
            };
        };
    };
    get_llm_settings_v1_projects__slug__llm_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_llm_settings_v1_projects__slug__llm_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LLMSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMSettingsOut"];
                };
            };
            /** @description Unknown provider, or enabled=true while clearing the api_key. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_test_v1_projects__slug__llm_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMTestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_llm_calls_v1_projects__slug__llm_calls_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMCallOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tenant_users__v1_tenant_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantUserOut"][];
                };
            };
        };
    };
    delete_tenant_user_v1_tenant_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Use logout to remove yourself. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cannot delete the owner. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not in this tenant. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_tenant_user_v1_tenant_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantUserPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantUserOut"];
                };
            };
            /** @description Cannot modify the owner; cannot grant the owner role here. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not in this tenant. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transfer_ownership_v1_tenant_transfer_ownership_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectMemberAddIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cannot transfer to yourself. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Target user not in this tenant. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invites_v1_invites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteOut"][];
                };
            };
        };
    };
    create_invite_v1_invites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteOut"];
                };
            };
            /** @description User already in this tenant; or invalid role; or unknown project_slug. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Owner role cannot be invited. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_invite_v1_invites__invite_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invite_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invite not in this tenant or already used. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_invite_v1_invites_preview_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitePreviewOut"];
                };
            };
            /** @description Invalid or expired token. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_invite_v1_invites_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteAcceptIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or expired token. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_v1_projects__slug__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantUserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_v1_projects__slug__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectMemberAddIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not in this tenant. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User is already a member. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_v1_projects__slug__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User is not a member of this project. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_v1_internal_ingest_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redeem_link_v1_internal_redeem_link_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedeemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_reply_v1_internal_ingest_reply_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestReplyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    outbound_pending_v1_internal_outbound_pending_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboundItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    outbound_ack_v1_internal_outbound_ack_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutboundAckIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
