/**
 * Placeholder OpenAPI types.
 *
 * Generated by `pnpm gen:api` against the running feedbot-api (F2 wires this).
 * Until then, this minimal skeleton lets the app type-check without any
 * real surface — every page that needs typed endpoints will fail loud
 * once codegen replaces this file.
 */

export interface paths {
	// Will be filled in by openapi-typescript codegen.
}

export type components = Record<string, never>;
