import createClient from 'openapi-fetch';
// types/api.ts is generated by `pnpm gen:api` (openapi-typescript reading from
// the running feedbot-api). Until F2 is merged, we ship a tiny placeholder so
// the app type-checks; once codegen is live, this import resolves to real types.
import type { paths } from '@/types/api';

/**
 * Single API client used everywhere. Cookies are httpOnly + SameSite=Strict
 * and the request flows through the same-origin Caddy proxy at /api/* —
 * no CORS, no manual `credentials: 'include'`.
 */
export const api = createClient<paths>({
	baseUrl: '/api',
	credentials: 'same-origin',
});

/**
 * Narrow openapi-fetch errors into something we can match on.
 * Most pages will surface this via toasts.
 */
export class ApiError extends Error {
	readonly status: number;
	readonly body: unknown;
	constructor(status: number, message: string, body: unknown) {
		super(message);
		this.name = 'ApiError';
		this.status = status;
		this.body = body;
	}
}

export async function unwrap<T>(
	promise: Promise<{
		data?: T;
		error?: unknown;
		response: Response;
	}>,
): Promise<T> {
	const { data, error, response } = await promise;
	if (error || !response.ok) {
		const message =
			(error as { detail?: string } | undefined)?.detail ??
			`Request failed: ${response.status} ${response.statusText}`;
		throw new ApiError(response.status, message, error);
	}
	if (data === undefined) {
		throw new ApiError(
			response.status,
			'Empty response',
			null,
		);
	}
	return data;
}
